git:
  depth: 1

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .
  - python -c 'from pyvims import VIMS'
script:
  - pip install -r tests/requirements.txt
  - pytest tests/
  - pytest --nbval-lax notebooks/pyvims.ipynb notebooks/VIMS_wvlns.ipynb
