language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - python setup.py develop
  - python -c 'from pyvims import VIMS'
  - pip install -r tests/requirements.txt
script:
  - pytest tests/
  - pytest --nbval-lax notebooks/pyvims.ipynb
