package:
  name: pyvims
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: .

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -v "

requirements:
  build:
    - python {{ python }}
    - pip 19.*
    - pbr
  run:
    - python {{ python }}
    - pbr
    - numpy
    - matplotlib
    - scipy
    - tqdm
    - requests
    - pvl

test:
  imports:
    - pyvims

about:
  home: https://github.com/seignovert/pyvims
  license: MIT
  license_family: MIT
  summary: Python package to manipulate the Cassini VIMS data.

extra:
  recipe-maintainers:
    - seignovert
